server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aplus
    username: rapil
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          format_sql: true
          show_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
